name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e
          OUTPUT=$(npx jsr publish)
          echo "$OUTPUT"
          if echo "$OUTPUT" | grep -q "Warning: Skipping, already published"; then
            echo "Error: The package has already been published. Please increment the version number."
            exit 1
          fi
